# Generated by Django 4.1.3 on 2022-11-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_item_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('usd', 'Usd'), ('rub', 'Rub')], default='usd', max_length=20, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'Usd'), ('rub', 'Rub')], default='usd', max_length=20, verbose_name='currency'),
        ),
    ]
