# Generated by Django 4.1.3 on 2022-11-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_discount_tax_alter_order_items_alter_orderitem_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'discount', 'verbose_name_plural': 'discounts'},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name': 'tax', 'verbose_name_plural': 'taxes'},
        ),
        migrations.AddField(
            model_name='tax',
            name='inclusive',
            field=models.BooleanField(default=False, verbose_name='inclusive'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent_off',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='percent off'),
        ),
    ]
