# Generated by Django 4.1.3 on 2022-11-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_discount_options_alter_tax_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'Usd'), ('RUB', 'Rub')], default='RUB', max_length=20, verbose_name='currency'),
        ),
    ]
