# Generated by Django 4.1.3 on 2022-11-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'Usd'), ('RUB', 'Rub')], default='USD', max_length=20, verbose_name='currency'),
        ),
    ]
