# Generated by Django 4.1.3 on 2022-11-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_order_currency_alter_item_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['name'], 'verbose_name': 'discount', 'verbose_name_plural': 'discounts'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['name'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'ordered item', 'verbose_name_plural': 'ordered items'},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'ordering': ['name'], 'verbose_name': 'tax', 'verbose_name_plural': 'taxes'},
        ),
    ]
