# Generated by Django 4.1.3 on 2023-02-12 14:56

from django.db import migrations


def create_items(apps, schema_editor):
    Item = apps.get_model("payments", "Item")
    item_1 = Item(name="Tea",
                  description="Tasty black tea",
                  price=10000,
                  currency="rub"
                  )
    item_1.save()

    item_2 = Item(name="Coffee",
                  description="Coffee from Ethiopia",
                  price=50000,
                  currency="rub"
                  )
    item_2.save()

    item_3 = Item(name="Chocolate",
                  description="Mars chocolate bar",
                  price=200,
                  currency="usd"
                  )
    item_3.save()

    item_4 = Item(name="Lemonade",
                  description="Coca-Cola 2 litres bottle",
                  price=300,
                  currency="usd"
                  )
    item_4.save()


def create_discount(apps, schema_editor):
    Discount = apps.get_model("payments", "Discount")
    discount = Discount(name="Christmas Sale", percent_off=20.5)
    discount.save()


def create_tax(apps, schema_editor):
    Tax = apps.get_model("payments", "Tax")
    tax = Tax(name="VAT", percentage=20.00)
    tax.save()


def create_orders(apps, schema_editor):
    Order = apps.get_model("payments", "Order")
    OrderItem = apps.get_model("payments", "OrderItem")
    Discount = apps.get_model("payments", "Discount")
    Tax = apps.get_model("payments", "Tax")
    Item = apps.get_model("payments", "Item")

    discount = Discount.objects.get(id=1)
    tax = Tax.objects.get(id=1)

    order_1 = Order(name="Drinks Order",
                    description="Ordering tea and coffee",
                    discount=discount,
                    tax=tax,
                    currency="rub")
    order_1.save()

    order_2 = Order(name="Another Order",
                    description="Ordering lemonade and chocolate",
                    tax=tax,
                    currency="usd")
    order_2.save()

    item_1 = Item.objects.get(id=1)
    item_2 = Item.objects.get(id=2)
    item_3 = Item.objects.get(id=3)
    item_4 = Item.objects.get(id=4)

    order_item_1 = OrderItem(order=order_1, item=item_1, quantity=7)
    order_item_1.save()

    order_item_2 = OrderItem(order=order_1, item=item_2, quantity=3)
    order_item_2.save()

    order_item_3 = OrderItem(order=order_2, item=item_3, quantity=12)
    order_item_3.save()

    order_item_4 = OrderItem(order=order_2, item=item_4, quantity=9)
    order_item_4.save()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_discount_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_items),
        migrations.RunPython(create_discount),
        migrations.RunPython(create_tax),
        migrations.RunPython(create_orders),
    ]
