services:
  db:
    image: postgres
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
    env_file:
      - payments_backend/.env.sample
    ports:
      - "5432:5432"
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - payments_backend/.env.sample
    depends_on:
      - db
    entrypoint: /entrypoint.sh
